# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: alyssa frazee
email: alyssa.frazee@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alyssafrazee.com" # the base hostname & protocol for your site
twitter_username: acfrazee
github_username:  alyssafrazee

plugins: [kramdown]
# Build settings
markdown: kramdown
